### PR TITLE
ENH: Use Time widgets for Override fields

### LINKED ISSUE #2: Date/Time for Override
Either an embedded ms calculator, for translation from Months/Weeks/Days/Hours/Minutes or some other way to enter a time for the overrides time.

### PR DESCRIPTION
**Pull request by hhslepicka**
Please ignore the string fields damaged by gateway issues.
**We will need to test that with a PLC to make sure the fields are being set properly.**
image

Closes #2

### CODE REVIEW

**Comment by ZLLentz** [comment]
Is this worth testing during the upcoming POMM? I'm happy to do the test.

**Comment by hhslepicka** [comment]
@ZLLentz this is pending PLC changes by @slacAWallace so can't really test it this POMM.

**Comment by ZLLentz** [comment]
Ok no worries, just checking the PRs here since I noticed there were zero watchers on the repo

**Comment by ZLLentz** [comment]
Hi Hugo, I'm going to continue and finish out this one on my branch, starting from your commits, so you don't have to see all the notifications here. Thank you!

**Comment by hhslepicka** [comment]
Hey @ZLLentz sounds good! Thanks!

**Pull request closed without merging**
